name: Verify Pipeline
on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: 872632
          private-key: ${{ secrets.PRIVATE_KEY }}
